version: '3.0'
services:
  db:
    image: postgres:10-alpine
    container_name: "postgres"
    #environment:
    #POSTGRES_DB: app
    #POSTGRESS_USER: postgres
    #POSTGRESS_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    container_name: "node"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_DB: app
      POSTGRESS_USER: postgres
      POSTGRESS_PASSWORD: postgres
      POSTGRESS_HOST: db

